INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DOCUMENT_LIST', 'en', 'Documents list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DOCUMENT_LIST', 'it', 'Lista documenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_RETURN_DETAIL_DOCUMENT', 'en', 'Return to project details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_RETURN_DETAIL_DOCUMENT', 'it', 'Ritorna dettaglio progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPLOAD_ENTANDO ', 'en', 'Upload in Entando');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPLOAD_ENTANDO ', 'it', 'Carica in Entando');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPLOAD_PROTECTED ', 'en', 'Upload as protected resource');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPLOAD_PROTECTED ', 'it', 'Carica come risorsa protetta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TRASH_ATTACHMENT_LABEL ', 'en', 'Trash document');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TRASH_ATTACHMENT_LABEL ', 'it', 'Cancella documento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TRASH_ATTACHMENT_TITLE ', 'en', 'Trash document');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TRASH_ATTACHMENT_TITLE ', 'it', 'Cancella documento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOAD_DOC', 'en', 'Document Upload');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOAD_DOC', 'it', 'Upload documenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DOCUMENT_DELETE', 'en', 'Document delete');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DOCUMENT_DELETE', 'it', 'Cancellazione documento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DEL_DOC', 'en', 'Confirm document deletion');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DEL_DOC', 'it', 'Conferma cancellazione documento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_NAME', 'en', 'Project:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_NAME', 'it', 'Project:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DOCUMENT_NAME', 'en', 'File name:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DOCUMENT_NAME', 'it', 'Nome del file:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_ATTACHMENT', 'en', 'Delete');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_ATTACHMENT', 'it', 'Cancella');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_RETURN_DOCUMENT_LIST', 'en', 'Return to list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_RETURN_DOCUMENT_LIST', 'it', 'Ritorna alla lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NO_DOCUMENTS', 'en', 'This project contains no documents');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NO_DOCUMENTS', 'it', 'Questo progetto non contiene documenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_REPOSITORY_NAME', 'en', 'Repository name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_REPOSITORY_NAME', 'it', 'Nome del repository');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NO_BRANCHES', 'en', 'No branches found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NO_BRANCHES', 'it', 'Nessuna branch trovata');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NO_COMMITS', 'en', 'No commits found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NO_COMMITS', 'it', 'Nessun commit trovato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NO_PULL_REQUEST', 'en', 'No pull requests found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NO_PULL_REQUEST', 'it', 'Nessuna pull request trovata');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NO_COMMITS', 'en', 'No commits found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NO_COMMITS', 'it', 'Nessun commit trovato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_ACTION_ERRORS', 'en', 'There are errors:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_ACTION_ERRORS', 'it', 'Errori rilevati:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_ACTION_MESSAGES', 'en', 'Messages:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_ACTION_MESSAGES', 'it', 'Messaggi:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_ACTION_ERRORS', 'en', 'There are errors:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_ACTION_ERRORS', 'it', 'Errori rilevati:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_FIELD_ERRORS', 'en', 'Field errors:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_FIELD_ERRORS', 'it', 'Errori nei campi:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_ACTION_MESSAGES', 'en', 'Messages:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_ACTION_MESSAGES', 'it', 'Messaggi:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_BACK_PROJECT_ENTRY', 'en', 'Back');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_BACK_PROJECT_ENTRY', 'it', 'Indietro');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NEW_PREQ', 'en', 'Create');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NEW_PREQ', 'it', 'Crea');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_title', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_title', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_body', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_body', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_PR_LIST', 'en', 'Pull request list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_PR_LIST', 'it', 'Lista pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE', 'en', 'page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE', 'it', 'pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_MODEL', 'en', 'page model');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_MODEL', 'it', 'modello pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_TITLE', 'en', 'page title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_TITLE', 'it', 'titolo pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('RESERVED_AREA', 'en', 'Please sign in');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('RESERVED_AREA', 'it', 'È necessario autenticarsi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USERNAME', 'en', 'Username');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USERNAME', 'it', 'Utente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PASSWORD', 'en', 'Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PASSWORD', 'it', 'Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SIGNIN', 'en', 'Sign in');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SIGNIN', 'it', 'Entra');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NOT_ALLOWED', 'en', 'User not allowed');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NOT_ALLOWED', 'it', 'Utente non autorizzato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_NOT_FOUND', 'en', 'Page not found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_NOT_FOUND', 'it', 'Pagina non trovata');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('GENERIC_ERROR', 'en', 'Generic Error');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('GENERIC_ERROR', 'it', 'Errore Generico');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC', 'it', 'Normale');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC', 'en', 'Normal');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT', 'it', 'Avanzata');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT', 'en', 'Advanced');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO', 'it', 'Accedi con client normale');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO', 'en', 'Go to the administration with normal client');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO', 'it', 'Accedi con client avanzato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO', 'en', 'Go to the administration with advanced client');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_FROM', 'en', 'From');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_FROM', 'it', 'Da');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_TO', 'en', 'To');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_TO', 'it', 'A');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('TEXT', 'en', 'Text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('TEXT', 'it', 'Testo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ALL', 'en', 'All');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ALL', 'it', 'Tutte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_FROM', 'en', 'From');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_FROM', 'it', 'Da');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_TO', 'en', 'To');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_TO', 'it', 'A');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCES', 'it', 'Risorse API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCES', 'en', 'API Resources');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_ERROR', 'it', 'Errore');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_ERROR', 'en', 'Errors');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE', 'it', 'Risorsa');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE', 'en', 'Resource');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS', 'it', 'Vai al dettaglio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS', 'en', 'Go to details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST', 'it', 'Elenco Servizi API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST', 'en', 'Service List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE', 'it', 'Servizio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE', 'en', 'Service');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF', 'it', 'Non Attivo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF', 'en', 'Not Active');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE', 'it', 'Attivo, Accesso Libero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE', 'en', 'Active, Free Access');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH', 'it', 'Attivo, Utenti Registrati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH', 'en', 'Active, Registered Users');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK', 'it', 'Metodo Attivo, Utenti Registrati con Autorizzazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK', 'en', 'Active, Registered Users with Permission');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA', 'it', 'Metodo Non Disponibile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA', 'en', 'Method Not Available');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES', 'it', 'Non ci sono Risorse API disponibili.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES', 'en', 'No API Resources available at the moment.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY', 'it', 'La tabella elenaca le Risorse API disponibile nel sistema. Nome della risorsa, la sua descrizione e lo stato di ciascun metodo.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY', 'en', 'The table lists the API Resources available in the system. Method name, description, group and the status of each method.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE', 'it', 'Namespace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE', 'en', 'Namespace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE', 'it', 'Sorgente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE', 'en', 'Source');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI', 'it', 'URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI', 'en', 'URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION', 'it', 'Estensione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION', 'en', 'Extension');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE', 'it', '''.xml'' per la risposta in formato xml e ''.json'' per la risposta in formato json.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE', 'en', '''.xml'' for response in xml format and ''.json'' for json.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_KO', 'it', 'Non disponibile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_KO', 'en', 'Not available');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD', 'it', 'Metodo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD', 'en', 'Method');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_OK', 'it', 'Disponibile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_OK', 'en', 'Available');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION', 'it', 'Autorizzazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION', 'en', 'Authorization');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE', 'it', 'Nessuna, questo metodo è pubblico');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE', 'en', 'None, this method is public');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM', 'it', 'Utenti registrati con permesso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM', 'en', 'Registered users with permission');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE', 'it', 'Utenti registrati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE', 'en', 'Registered users');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS', 'it', 'Schema XML');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS', 'en', 'XML Schemas');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ', 'it', 'Richiesta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ', 'en', 'Request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP', 'it', 'Risposta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP', 'en', 'Response');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM', 'it', 'Questa tabella mostra i parametri per la richiesta del metodo. Per ciascuno di essi ci sono tre colonne: il nome del parametro, la descrizione del parametro e l''indicazione di obbligatorietà.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM', 'en', 'This table shows the request parameters for this method. For each of them there are three columns: the parameter name, the parameter description and whether if it''s mandatory or not.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS', 'it', 'Parametri');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS', 'en', 'Parameters');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_NAME', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_NAME', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED', 'en', 'Mandatory');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('YES', 'it', 'Si');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('YES', 'en', 'Yes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NO', 'it', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NO', 'en', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('BOTH', 'it', 'Entrambi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('BOTH', 'en', 'Both');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_LIST', 'it', 'Lista delle Risorse API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_LIST', 'en', 'API Resource List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_PREV', 'it', 'Indietro');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_PREV', 'en', 'Previous');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_NEXT', 'it', 'Ancora');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_NEXT', 'en', 'Next');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_FIRST', 'it', 'Inizio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_FIRST', 'en', 'Start');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_LAST', 'it', 'Fine');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_LAST', 'en', 'End');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_STEP_BACKWARD', 'it', 'Indietro di');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_STEP_BACKWARD', 'en', 'Previous');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_STEP_FORWARD', 'it', 'Avanti di');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGER_STEP_FORWARD', 'en', 'Next');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CATEGORY', 'it', 'Categoria');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CATEGORY', 'en', 'Category');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('IGNORE', 'it', 'Ignora');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('IGNORE', 'en', 'Ignore');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ERRORS', 'it', 'Oops! Hai sbagliato qualcosa!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ERRORS', 'en', 'Whoops! You''re doing it wrong!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_CONFIGURATION', 'it', 'Configura il profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_CONFIGURATION', 'en', 'Edit profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_CONFIRM_NEWPASS', 'it', 'Conferma nuova password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_CONFIRM_NEWPASS', 'en', 'Confirm new password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_EDITPASSWORD', 'it', 'Modifica Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_EDITPASSWORD', 'en', 'Edit Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_EDITPASSWORD_TITLE', 'it', 'Modifica Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_EDITPASSWORD_TITLE', 'en', 'Edit Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_EDITPROFILE_TITLE', 'it', 'Modifica profilo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_EDITPROFILE_TITLE', 'en', 'Edit Profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEUP', 'it', 'Sposta su');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEUP', 'en', 'Move up');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEUP_IN', 'it', 'Sposta su in posizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEUP_IN', 'en', 'Move at position');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN', 'it', 'Sposta giu');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN', 'en', 'Move down');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN_IN', 'it', 'Sposta giu in posizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN_IN', 'en', 'Move down at position');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_REMOVE', 'it', 'Rimuovi dalla lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ITEM_REMOVE', 'en', 'Remove from list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_MESSAGE_TITLE_FIELDERRORS', 'it', 'Attenzione, si sono verificati i seguenti errori nella compilazione del modulo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_MESSAGE_TITLE_FIELDERRORS', 'en', 'Warning, please check the module');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_NEWPASS', 'it', 'Nuova password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_NEWPASS', 'en', 'New password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_OLDPASSWORD', 'it', 'Vecchia password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_OLDPASSWORD', 'en', 'Old password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PASSWORD_UPDATED', 'it', 'La password è stata aggiornata correttamente.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PASSWORD_UPDATED', 'en', 'Your password updated successfully.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PLEASE_LOGIN', 'it', 'E'' necessario effettuare l''accesso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PLEASE_LOGIN', 'en', 'Please login');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PLEASE_LOGIN_AGAIN', 'it', 'E'' necessario riloggarsi.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PLEASE_LOGIN_AGAIN', 'en', 'Please logout and login again.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD', 'it', 'E'' necessario effettuare l''accesso per cambiare la password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD', 'en', 'Please login in order to change your password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PROFILE_UPDATED', 'it', 'Profilo aggiornato correttamente.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PROFILE_UPDATED', 'en', 'Your profile is now updated.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_SAVE_PASSWORD', 'it', 'Salva password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_SAVE_PASSWORD', 'en', 'Save password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_SAVE_PROFILE', 'it', 'Salva il profilo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_SAVE_PROFILE', 'en', 'Save profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ADDITEM_LIST', 'it', 'Aggiungi nuovo elemento alla lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ADDITEM_LIST', 'en', 'Add an element to the list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_YES', 'it', 'Si');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_YES', 'en', 'Yes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_NO', 'it', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_NO', 'en', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_BOTH_YES_AND_NO', 'it', 'Indifferente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_BOTH_YES_AND_NO', 'en', 'Both');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT', 'it', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT', 'en', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL', 'en', 'Mandatory');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT', 'it', 'Min');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT', 'en', 'Min');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL', 'it', 'Lunghezza Minima');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL', 'en', 'Minimum length');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT', 'it', 'Max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT', 'en', 'Max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL', 'it', 'Lunghezza Massima');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL', 'en', 'Maximum length');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_CURRENT_USER_WITHOUT_PROFILE', 'it', 'Utente corrente senza profilo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_CURRENT_USER_WITHOUT_PROFILE', 'en', 'Current user without profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY', 'en', 'Key');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY', 'it', 'Id');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API', 'en', 'Parent API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API', 'it', 'API Padre');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION', 'en', 'Authorization');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION', 'it', 'Autorizzazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE', 'en', 'Free');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE', 'it', 'Accesso Libero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_URI', 'en', 'URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_URI', 'it', 'URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS', 'en', 'Parameters');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS', 'it', 'Parametri');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_FILTERS_BUTTON', 'en', 'Narrow your search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_FILTERS_BUTTON', 'it', 'Filtra ulteriormente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LIST_VIEWER_EMPTY', 'en', 'No result found. Broaden your search and try again!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LIST_VIEWER_EMPTY', 'it', 'Nessun risultato trovato. Imposta dei parametri meno stringenti e prova ancora!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD', 'en', 'The value for field');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD', 'it', 'Il valore del campo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT', 'en', 'is invalid');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT', 'it', 'non è corretto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_THIS_CONTENT', 'en', 'Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_THIS_CONTENT', 'it', 'Modifica');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS', 'en', 'Search Result');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS', 'it', 'Risultati della Ricerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCHED_FOR', 'en', 'You searched for');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCHED_FOR', 'it', 'Hai cercato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_NOTHING_FOUND', 'en', 'No result found. Try another search term!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_NOTHING_FOUND', 'it', 'Nessun risultato trovato. Prova a cercare un altro termine!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_INTRO', 'en', 'Found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_INTRO', 'it', 'Sono stati trovati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_OUTRO', 'en', 'results. Showing:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_OUTRO', 'it', 'risultati. Mostrati:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TITLE_LOGIN', 'en', 'Basecamp Sign In');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TITLE_LOGIN', 'it', 'Accedi a Basecamp');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOGIN_NOW', 'en', 'Sign In');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOGIN_NOW', 'it', 'Connettiti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOGOUT', 'en', 'Sign Out');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOGOUT', 'it', 'Esci');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOGIN_OK', 'en', 'You are signed in with your Basecamp account');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LOGIN_OK', 'it', 'Hai effettuato l''accesso con il tuo account Basecamp');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_CREATEDAT', 'en', 'Created at');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_CREATEDAT', 'it', 'Creato il');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPDATEDAT', 'en', 'Updated at');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPDATEDAT', 'it', 'Aggiornato il');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NEW_PROJECT', 'en', 'New project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NEW_PROJECT', 'it', 'Nuovo progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_NAME', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_NAME', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_DESCRIPTION', 'it', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_EDIT_PROJECT', 'en', 'Edit project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_EDIT_PROJECT', 'it', 'Modifica progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LIST_PROJECTS', 'en', 'Projects list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LIST_PROJECTS', 'it', 'Lista progetti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_SEARCH_TEXT', 'en', 'Text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_SEARCH_TEXT', 'it', 'Testo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_GOTO_LIST', 'en', 'Nevermind');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_GOTO_LIST', 'it', 'Ritorna alla lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_VIEW_PROJECT', 'en', 'Project Details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_VIEW_PROJECT', 'it', 'Dettaglio progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_TRASH', 'en', 'Delete project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_TRASH', 'it', 'Cancella il progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_CONFIRM', 'en', 'Do you really want to delete the project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_CONFIRM', 'it', 'Cancellare il progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE', 'en', 'Delete');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE', 'it', 'Cancella');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_CREATED', 'en', 'Creation date');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_CREATED', 'it', 'Data creazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_UPDATED', 'en', 'Updated at');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_UPDATED', 'it', 'Ultimo aggiornamento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_DRAFT', 'en', 'Draft');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_DRAFT', 'it', 'Bozza');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_STARRED', 'en', 'Starred');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_STARRED', 'it', 'Preferito');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_ISCLIENTPROJECT', 'en', 'Client project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_ISCLIENTPROJECT', 'it', 'Progetto di clienti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_VIEW', 'en', 'View Details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_VIEW', 'it', 'Mostra dettagli');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_TODOLISTS', 'en', 'Todo list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_TODOLISTS', 'it', 'Todo list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_NO_TODOS', 'en', 'No todo defined!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_NO_TODOS', 'it', 'Nessun todo definito!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_NO_COMPLETED', 'en', 'No todo completed!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_NO_COMPLETED', 'it', 'Nessun todo completato!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_NO_REMAINING', 'en', 'No todo remaining');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_NO_REMAINING', 'it', 'Nessun todo rimanente!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_REMAINING', 'en', 'Remaining todo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_REMAINING', 'it', 'Todo rimanenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_COMPLETED', 'en', 'Completed Todo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_COMPLETED', 'it', 'Todo completati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_NEW', 'en', 'New todo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODO_NEW', 'it', 'New todo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODOLIST_NEW', 'en', 'New todo list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODOLIST_NEW', 'it', 'Nuova lista Todo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_INCLUDE_ARCHIVED', 'en', 'Include archived projects');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_INCLUDE_ARCHIVED', 'it', 'Include progetti archiviati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_SEARCH_STARRED', 'en', 'Consider only starred project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_SEARCH_STARRED', 'it', 'Considera solo i progetti preferiti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_SEARCH_CLIENT', 'en', 'Consider only client projects');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_SEARCH_CLIENT', 'it', 'Considera solo i progetti clienti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_SEARCH_TRASHED', 'en', 'Consider only trashed projects');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_SEARCH_TRASHED', 'it', 'Considera solo progetti cancellati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NWS_ATTACHMENTS', 'en', 'Attachments');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NWS_ATTACHMENTS', 'it', 'Allegati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NWS_LINKS', 'en', 'Links');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NWS_LINKS', 'it', 'Link');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NWS_READ_MORE', 'en', 'View details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NWS_READ_MORE', 'it', 'Continua');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_WELCOME', 'en', 'Hello');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_WELCOME', 'it', 'Ciao');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_ADMINISTRATION', 'en', 'Administration');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_ADMINISTRATION', 'it', 'Amministrazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_SIGNOUT', 'en', 'Sign out');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_SIGNOUT', 'it', 'Esci');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_SIGNIN', 'en', 'Sign in');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_SIGNIN', 'it', 'Accedi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_USER_STATUS_EXPIRED', 'en', 'Your account has expired!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_BODY', 'it', 'Body');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_USER_STATUS_EXPIRED', 'it', 'Credenziali scadute!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_USER_STATUS_CREDENTIALS_INVALID', 'en', 'Wrong username or password!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_USER_STATUS_CREDENTIALS_INVALID', 'it', 'Le credenziali non sono corrette!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_USERNAME', 'en', 'Username');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_USERNAME', 'it', 'Utente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_PASSWORD', 'en', 'Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLF_PASSWORD', 'it', 'Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLC_LANGUAGE', 'en', 'Language');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLC_LANGUAGE', 'it', 'Lingua');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLC_LANG_it', 'en', 'Italiano');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLC_LANG_it', 'it', 'Italiano');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLC_LANG_en', 'en', 'English');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESLC_LANG_en', 'it', 'English');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESSF_SEARCH', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESSF_SEARCH', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESNB_YOU_ARE_HERE', 'en', 'You are here');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ESNB_YOU_ARE_HERE', 'it', 'Sei qui');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CNG_ATTACHMENTS', 'en', 'Attachments');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CNG_ATTACHMENTS', 'it', 'Allegati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CNG_LINKS', 'en', 'Links');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CNG_LINKS', 'it', 'Link');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CNG_READ_MORE', 'en', 'View details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CNG_READ_MORE', 'it', 'Continua');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('COPYRIGHT', 'en', 'Copyright &copy; My Company YYYY');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('COPYRIGHT', 'it', 'Copyright &copy; Mia Azienda AAAA');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PORTAL_TITLE', 'en', 'My Portal');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PORTAL_TITLE', 'it', 'Il Mio Portale');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_ID', 'en', 'id');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_ID', 'it', 'id');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_ORGANIZATION', 'en', 'organization');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_ORGANIZATION', 'it', 'organization');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_API_KEY', 'en', 'api_key');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_API_KEY', 'it', 'api_key');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_API_SECRET', 'en', 'api_secret');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_API_SECRET', 'it', 'api_secret');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_TOKEN', 'en', 'token');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_TOKEN', 'it', 'token');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_ACTIONS', 'it', 'Actions');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_ACTIONS', 'en', 'Actions');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_NEW', 'it', 'Params New');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_NEW', 'en', 'Params New');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_EDIT', 'it', 'Params Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_EDIT', 'en', 'Params Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_TRASH', 'it', 'Params Trash');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_TRASH', 'en', 'Params Trash');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_TRASH_CONFIRM', 'it', 'Params Trash confirm');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_TRASH_CONFIRM', 'en', 'Params Trash confirm');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_SEARCH_PARAMS', 'it', 'Params search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_SEARCH_PARAMS', 'en', 'Params search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_NOT_FOUND', 'it', 'Params not found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jptrello_PARAMS_NOT_FOUND', 'en', 'Params not found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_ID', 'en', 'id');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_ID', 'it', 'id');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_USERNAME', 'en', 'username');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_USERNAME', 'it', 'username');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_PASSWORD', 'en', 'password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_PASSWORD', 'it', 'password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_JENKINS_URL', 'en', 'jenkins_url');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_JENKINS_URL', 'it', 'jenkins_url');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_TOKEN', 'en', 'token');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_TOKEN', 'it', 'token');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_ACTIONS', 'it', 'Actions');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_ACTIONS', 'en', 'Actions');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_NEW', 'it', 'Params New');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_NEW', 'en', 'Params New');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_EDIT', 'it', 'Params Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_EDIT', 'en', 'Params Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_TRASH', 'it', 'Params Trash');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_TRASH', 'en', 'Params Trash');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_TRASH_CONFIRM', 'it', 'Params Trash confirm');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_TRASH_CONFIRM', 'en', 'Params Trash confirm');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_SEARCH_PARAMS', 'it', 'Params search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_SEARCH_PARAMS', 'en', 'Params search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_NOT_FOUND', 'it', 'Params not found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpjenkins_PARAMS_NOT_FOUND', 'en', 'Params not found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('POST_TEST_LABEL', 'en', 'Giseppe rulez');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('POST_TEST_LABEL', 'it', 'Giseppe regna');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_YOU_HAVE_NO_AVATAR', 'en', 'You don''t have an avatar');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_YOU_HAVE_NO_AVATAR', 'it', 'Non hai nessun avatar');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_CURRENT_AVATAR', 'it', 'Avatar corrente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_CURRENT_AVATAR', 'en', 'Current Avatar');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_CONFIRM_DELETE', 'en', 'Do You really want to remove your avatar?');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_CONFIRM_DELETE', 'it', 'Vuoi davvero eliminare l''avatar?');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_AVATAR_SAVED', 'en', 'Avatar successfully saved');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_AVATAR_SAVED', 'it', 'Avatar salvato correttamente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_TITLE', 'it', 'Avatar');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_TITLE', 'en', 'Avatar');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_DELETE', 'it', 'Rimuovi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_DELETE', 'en', 'Remove');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_UPLOAD', 'it', 'Carica un''immagine');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_UPLOAD', 'en', 'Upload an image');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_GO_UPLOAD', 'it', 'Carica');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_GO_UPLOAD', 'en', 'Upload');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_OK_THANKYOU', 'it', 'Ok');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpavatar_OK_THANKYOU', 'en', 'Ok');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_commits:', 'en', 'Commits list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_commits:', 'it', 'Lista di commit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_entry', 'en', 'Current project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_entry', 'it', 'Progetto corrente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_current', 'en', 'Current branch');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_current', 'it', 'Branch in uso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_branches', 'en', 'Branch selection');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_branches', 'it', 'Seleziona branch ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_SET_BRANCH', 'en', 'Set branch');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_SET_BRANCH', 'it', 'Scegli branch');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PULL_REQUEST_LIST', 'en', 'Pull request list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PULL_REQUEST_LIST', 'it', 'Lista pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PULL_REQUEST_NEW', 'en', 'Create a pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PULL_REQUEST_NEW', 'it', 'Crea una pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_by', 'en', 'Project by');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_by', 'it', 'Progetto di');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NUMBER', 'en', 'Number ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NUMBER', 'it', 'Numero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_TITLE', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_TITLE', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_BODY', 'en', 'Body');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_MERGED', 'en', 'Merged');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_MERGED', 'it', 'Mergiato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_ACCEPT_PULL_REQUEST', 'en', 'Accept pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_ACCEPT_PULL_REQUEST', 'it', 'Accetta pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_MERGEABLE', 'en', 'Mergeable');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_MERGEABLE', 'it', 'Mergiabile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NOT_MERGEABLE', 'en', 'Not mergeable');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_NOT_MERGEABLE', 'it', 'Non mergiabile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_TODO', 'en', 'Delete ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_TODO', 'it', 'Cancella ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_ASSIGN_TO', 'en', 'Assign to');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_ASSIGN_TO', 'it', 'Assegna a');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_SAVE', 'en', 'Save');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_SAVE', 'it', 'Salva');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPDATE_TODO', 'en', 'Update ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_UPDATE_TODO', 'it', 'Aggiorna ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_PR_NEW', 'en', 'Create a pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_PR_NEW', 'it', 'Crea una pull request ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_BASE_BRANCH', 'en', 'Base branch');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_BASE_BRANCH', 'it', 'Branch base');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_HEAD_BRANCH', 'en', 'Head branch ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_HEAD_BRANCH', 'it', 'Head branch');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODOLIST_NEW_NAME', 'en', 'New name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODOLIST_NEW_NAME', 'it', 'Nuovo nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODOLIST_NEW_DESCRIPTION', 'en', 'New description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_TODOLIST_NEW_DESCRIPTION', 'it', 'Nuova descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_NEW_TODO_TITLE', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_LABEL_NEW_TODO_TITLE', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_NAME', 'en', 'NAME');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_NAME', 'it', 'NOME');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_BUILD', 'en', 'BUILD');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_BUILD', 'it', 'BUILD');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_LOG', 'en', 'LOG');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_LOG', 'it', 'LOG');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_VALUE', 'en', 'VALUE');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jenkins_VALUE', 'it', 'VALORE');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('add_new_job', 'en', 'Add new job');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('add_new_job', 'it', 'Aggiungi nuovo lavoro');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('info_server', 'en', 'Server info');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('info_server', 'it', 'Informazioni server');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('welcome', 'en', 'Welcome on');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('welcome', 'it', 'Benvenuti su');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_MORE_RECENT', 'it', 'Le più recenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_MORE_VOTED', 'it', 'Le più votate');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_VOTE_AGREE', 'it', 'Mi piace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_VOTE_DISAGREE', 'it', 'Non mi piace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_LIKE_IT', 'it', 'Mi piace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_NOT_LIKE_IT', 'it', 'Non mi piace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_GO_TO', 'it', 'Torna alle');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_PUBBL', 'it', 'Scritta da');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_COMMENT_SAID', 'it', 'ha scritto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LABEL_TITLE', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAG_REMOVE', 'it', 'Elimina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SAVE_IDEA', 'it', 'Salva');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAG_JOIN', 'it', 'Associa');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SAVE_COMMENT', 'it', 'Commenta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_IDEA_TITLE', 'it', 'Ricerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_IDEAS', 'it', 'Cerca Idee');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_STATISTIC_TITLE', 'it', 'Statistiche');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_STATISTICS_EMPTY', 'it', 'Non ci sono statistiche');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SUBMIT_IDEA', 'en', 'Submit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SUBMIT_IDEA', 'it', 'Invia');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_DO_LOGIN', 'en', 'Sign in if you want to participate.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_DO_LOGIN', 'it', 'Accedi se vuoi partecipare.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_MORE_VOTED', 'en', 'Most Voted');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_VOTE_AGREE', 'en', 'I like it');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_VOTE_DISAGREE', 'en', 'I don''t like it');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_LIKE_IT', 'en', 'I like it');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_NOT_LIKE_IT', 'en', 'I don''t like it');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_GO_TO', 'en', 'Go to');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_PUBBL', 'en', 'Written by');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_COMMENT_SAID', 'en', 'said');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_COMMENT', 'en', 'Your comment');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_COMMENT', 'it', 'Il tuo commento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LABEL_TITLE', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LABEL_DESCR', 'en', 'Your entry');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LABEL_DESCR', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAG_REMOVE', 'en', 'Remove');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SAVE_IDEA', 'en', 'Save');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAG_JOIN', 'en', 'Join');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SAVE_COMMENT', 'en', 'Send Comment');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_IDEA_TITLE', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_IDEAS', 'en', 'Search Ideas');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_STATISTIC_TITLE', 'en', 'Stats');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_STATISTICS_EMPTY', 'en', 'No stats at the moment.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_NOIDEA_NOW', 'en', 'No Ideas at the moment.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_MORE_RECENT', 'en', 'Recent');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAG', 'en', 'Filed under');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAG', 'it', 'Categoria');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAGS_ALL', 'en', 'All');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAGS_ALL', 'it', 'Tutte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAGS_EMPTY', 'en', 'No tags available.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAGS_EMPTY', 'it', 'Non ci sono categorie disponibili.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAGS_TITLE', 'en', 'Tags');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TAGS_TITLE', 'it', 'Categorie');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_TITLE', 'en', 'Crowdsourcing Ideas');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_TITLE', 'it', 'Idee');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LIST_IDEA_TITLE', 'en', 'Entries');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LIST_IDEA_TITLE', 'it', 'Contributi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LIST_IDEA_FILTERED_BY', 'en', 'Filtered by');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LIST_IDEA_FILTERED_BY', 'it', 'Lista filtrata per');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LIST_IDEA_ALL', 'en', 'Remove the filter and view all');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_LIST_IDEA_ALL', 'it', 'Annulla il filtro');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TITLE_SEARCH', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_TITLE_SEARCH', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_FOR', 'en', 'Search for');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_FOR', 'it', 'Cerca testo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_IN_ALL', 'en', 'All categories');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_IN_ALL', 'it', 'Tutte le categorie');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_NEW_IDEA_TITLE', 'en', 'Quick entry');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_NEW_IDEA_TITLE', 'it', 'Contributo rapido');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_VOTES', 'en', 'Votes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_VOTES', 'it', 'Voti espressi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_COMMENTS', 'en', 'Comments');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_COMMENTS', 'it', 'Commenti inseriti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_USERS', 'en', 'Users involved');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_USERS', 'it', 'Utenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_PROPOSED_IDEAS', 'en', 'Proposed ideas');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_PROPOSED_IDEAS', 'it', 'Idee proposte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_REMOVEFILTER', 'en', 'Remove filter');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_REMOVEFILTER', 'it', 'Rimuovi filtro');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_NOIDEA_FOUND', 'en', 'No idea found.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_NOIDEA_FOUND', 'it', 'Nessuna idea trovata.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_NOT_FOUND', 'it', 'L''idea richiesta non è disponibile. Prova ad effettuare una ricerca.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_NOT_FOUND', 'en', 'Requested idea not found. Try using the search form.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_DETAILS', 'it', 'Dettagli Idea');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_IDEA_DETAILS', 'en', 'Idea Details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_INSTANCE', 'it', 'Istanza');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_INSTANCE', 'en', 'Instance');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_BACK_TO_LIST', 'it', 'Lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_BACK_TO_LIST', 'en', 'List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_RESULT', 'it', 'Risultati della ricerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcollaboration_SEARCH_RESULT', 'en', 'Search results');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('access', 'en', 'Access to');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('access', 'it', 'Accesso a ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_ENTRY', 'en', 'See the project on Github');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_ENTRY', 'it', 'Guarda il progetto su Github');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_PR_CONFIRM', 'en', 'Accept pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_PR_CONFIRM', 'it', 'Accetta pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_CONFIRM_PREQ', 'en', 'Confirm pull request ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_CONFIRM_PREQ', 'it', 'Conferma pull request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_FIELD_ERRORS', 'en', 'Error(s) found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_FIELD_ERRORS', 'it', 'Form compilazione errato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_MUST_LOGIN', 'en', 'Click on Sign in to access Basecamp first');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_MUST_LOGIN', 'it', 'Accedi a Basecamp cliccando su Sign in');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_RETURN_LIST', 'en', 'Back to Projects list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_RETURN_LIST', 'it', 'Torna a Lista progetti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_BACK_TO', 'en', 'Back to Basecamp');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_BACK_TO', 'it', 'Torna a Basecamp');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_ccd baseurrent', 'en', 'Basecamp project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_ccd baseurrent', 'it', 'Progetto Basecamp');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_NEW', 'en', 'Create new project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_NEW', 'it', 'Crea nuovo progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_SAVE', 'en', 'Save project');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROJECT_SAVE', 'it', 'Salva progetto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NO_PROJECTS', 'en', 'No projects found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_NO_PROJECTS', 'it', 'Nessun progetto trovato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_SAVE', 'en', 'Save');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_DELETE_SAVE', 'it', 'Salva');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROGRESS_BAR', 'en', 'ToDo status');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_PROGRESS_BAR', 'it', 'Stato dei ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_ADD_TODO', 'en', 'New ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpbasecamp_ADD_TODO', 'it', 'Nuovo ToDo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_repositories', 'en', 'Repositories list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_PROJECT_repositories', 'it', 'Lista repository');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_REPOSITORY', 'en', 'GitHub');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpgithub_REPOSITORY', 'it', 'GitHub');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PFL_fullname', 'en', 'Full Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('userprofile_PFL_email', 'en', 'Email');
